set nocompatible
set nu
set confirm
set cursorline
set hlsearch
set showmatch
set showcmd
set smartcase
set ruler
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set clipboard+=unnamed
filetype indent on

""" colorscheme """
"color ron
colorscheme molokai
let g:molokai_original = 1
syntax on

""" SQLComplete """
"let g:ftplugin_sql_omni_key = '<C-S>'

""" insert header for certain files """
au BufNewFile *.py 0r ~/.vim/headers/python.txt



""""""""""""""""""""""for Vundle"""""""""""""""""""""""""""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.

Plugin 'ervandew/supertab'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'klen/python-mode'
Plugin 'sukima/xmledit'
Plugin 'vim-scripts/SQLComplete.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

